### ISSUE TITLE
Release Features for v0.1.0

### ISSUE THREAD

**Issue by dotRollen** [codingpals/mycodingpal.io#2]
The concept of the application is to build an app that allows all developers to help them focus on learning. We'll open a discussion based on this premise and decide what the main features of the application will be for release version 0.1.0. 

All other features will be added to a wishlist for us to revisit once we release version 0.1.0.

- [x] Meet up for a discussion on core features to implement
- [x] Write the first draft of features with level of priority
- [x] Review as a team the first draft features
- [x] Update draft with notes from the review
- [x] Final draft of features  completed

**Comment by dotRollen** [comment]
Release version 0.1.0

User Features

- Local and Github registration - release version 0.1.0
- Hours spent - release version 0.1.0
- Pre, during, or post bootcamp/coding experience  -  (private) release version 0.1.0
- Language tags - release version 0.1.0
- Avatars - release version 0.1.0

Timer Feature

- Timer - release v0.1.0
- Alert when time is up
- Play time-up sound
- Save session time
- Daily quota - release v0.1.0
- DO IT, DO IT NOW Mode - release v0.1.0


Reading List Feature

- Review of books, bootcamps, video courses, tutorial sites - release v0.1.0
- User advice/preparation for each reading list item - release v0.1.0

**Comment by cimafrancad45** [comment]
Looks like everything we want in order for v0.1.0

**Comment by EricqyHan** [comment]
Looks good.

**Comment by Nikee-R** [comment]
Lookin good!

**Comment by cimafrancad45** [comment]
loks liek shet

**Comment by dicimafran** [comment]
Looks good.

**Comment by dotRollen** [comment]
Thank you everyone 👍
