### ISSUE TITLE
Libraries, Packages and Technologies

### ISSUE THREAD

**Issue by dotRollen** [codingpals/mycodingpal.io#5]
Requirements have been set by the stakeholders. We are required to use Node.js, React.js, Express, MongoDB and published on Heroku. We are also tasked to design a API that allows for RESTful communication with GET, POST, DELETE And PUT. There must be at least two libraries included in this project.

- [x] Review the features for release version 0.1.0
- [x] Research and draft list of libraries that best fit
- [x] Add relevant links and documentation to the libraries
- [x] Review as a team the list of libraries
- [x] Complete final draft of the list of libraries

**Comment by dotRollen** [comment]
## REST API to Consume

- Amazon for books - https://developer.amazon.com/services-and-apis 

## Frontend

- Foundation (https://foundation.zurb.com/templates.html)  - CSS Framework 
- Odometer (https://github.hubspot.com/odometer/) 
- Odometer is a Javascript and CSS library that creates smooth number transitioning. The library is extremely lightweight and performant as all 
- animations are handles in CSS with transforms. It supports Firefox, Safari, Chrome and IE8+, and has automatic fallback on older browsers
- React.js (https://reactjs.org/docs/getting-started.html) 
- Axios (https://www.npmjs.com/package/axios) 

## Backend 

- Node.js (https://nodejs.org/en/docs/) 
- Express.js (https://nodejs.org/en/docs/) 
- Passport.js (http://www.passportjs.org/) 
- Google Calendar API ( https://developers.google.com/calendar/ ) 
- Mongoose (https://mongoosejs.com/) 
- Moment.js (https://momentjs.com/) 
- SimpleMDE  (https://simplemde.com/) 
- Nodemailer (https://nodemailer.com/about/) 
- Get Data Reviews (https://market.mashape.com/munozbosch/get-data-reviews)

## Database

- MongoDB - (https://docs.mongodb.com/manual/core/document/) 

## Deployment

- Webpack - (https://webpack.js.org/ )

**Comment by cimafrancad45** [comment]
Looks like everything is in order.

**Comment by Nikee-R** [comment]
This looks good!

**Comment by dicimafran** [comment]
Goood!

**Comment by EricqyHan** [comment]
Good

**Comment by dotRollen** [comment]
Thank you everyone ! 👍
